id: regex('^[0-9a-f]{8}-[0-9a-f]{4}-[0-5][0-9a-f]{3}-[089ab][0-9a-f]{3}-[0-9a-f]{12}$')
title: str()
subtitle: str(required=False)
description: str(required=False)
version: any(int(), num(), str(), required=False)
category: int()
game:
  titleId: str()
  version: list(str())
emulator: list(int())
compatibility:
  whitelist: list(regex('^[0-9a-f]{8}-[0-9a-f]{4}-[0-5][0-9a-f]{3}-[089ab][0-9a-f]{3}-[0-9a-f]{12}$'), required=False)
  blacklist: list(regex('^[0-9a-f]{8}-[0-9a-f]{4}-[0-5][0-9a-f]{3}-[089ab][0-9a-f]{3}-[0-9a-f]{12}$'), required=False)
author: list(include('author_element'), required=False)
---
author_element:
  name: str()
  link: str(required=False)
