id: regex('^[0-9a-fA-F]{8}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{12}$')
title: str()
subtitle: str(required=False)
description: str(required=False)
version: str()
category: int()
game:
  titleId: str()
  version: list(str())
emulator: list(int())
compatibility:
  whitelist: list(regex('^[0-9a-fA-F]{8}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{12}$'))
  blacklist: list(regex('^[0-9a-fA-F]{8}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{12}$'))
author: list(includes('author_element'))

author_element:
  name: str()
  link: str(required=False)
