id: 217fcb79-612f-4191-a486-56b33e313522
title: Aspect ratio - 18-9
subtitle:
description:
version: 1.0.0
category: 3
game:
  titleId: 0100F2C0115B6000
  version:
    - 1.1.2
    - 1.1.1
    - 1.1.0
    - 1.0.0
emulator:
  - 1
compatibility:
  whitelist:
  blacklist:
author:
  - { name: 'Fayaz', link: 'https://gamebanana.com/mods/updates/443462' }
  - { name: 'Fruithapje21', link: 'https://github.com/Fruithapje21/TOTK-Ultrawide' }