name: Yamale Validation

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  # Choose the appropriate Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yamale

      - name: Run validation
        run: |
          find . -type f -name "config.yaml" -not -path "./config.yaml" > file_list.txt
          exit_code=0
          issues=""
          while IFS= read -r file; do
            echo "Validating file: $file"            
            validation_output=$(yamale -s schema.yaml "$file" 2>&1)
            if [ $? -ne 0 ]; then
              issues+="Validation failed for file: $file\n$validation_output\n"
              exit_code=1
            fi
          done < file_list.txt
          echo "$issues"
          exit $exit_code
