name: Yamale Validation

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  # Choose the appropriate Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yamale

      - name: Run validation
        run: |
          find . -type f -name "config.yaml" -o -print0 | xargs -0 -I {} sh -c 'echo "Validating file: {}"; yamale -s schema.yaml "{}" || (echo "Validation failed for file: {}"; exit 1)'
