name: Yamale Validation

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  # Choose the appropriate Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yamale

      - name: Run validation
        run: |
          find . -type f -name "config.yaml" -not -path "./config.yaml" > file_list.txt
          validation_failed=false
          while IFS= read -r file; do
            echo "Validating file: $file"
            if ! yamale -s schema.yaml "$file" > /dev/null 2>&1; then
              echo "Validation failed for file: $file"
              validation_failed=true
            fi
          done < file_list.txt
          if [ "$validation_failed" = true ]; then
            echo "Validation failed for one or more files."
            exit 1
          fi

